### ISSUE TITLE
Refuses to install despite Gcloud being installed.

### ISSUE THREAD

**Issue by taoszhanna** [GoogleCloudPlatform/iap-windows-rdc-plugin#10] opened 2019-09-10 18:58 UTC
The MSI installer exits with the message "Google Cloud SDK is not installed on this machine", despite running the msiexec /i CloudIap-Plugin-1.0.6.0.msi from the Google Cloud Shell. 

>gcloud --version
Google Cloud SDK 262.0.0
beta 2019.05.17
bq 2.0.47
core 2019.09.06
gsutil 4.42

**Comment by taoszhanna** [comment] 2019-09-10 22:43
I was able to get this working with the following steps:

-Manually extract the contents of the MSI
-Manually copy the .dll files to C:\Program Files (x86)\Microsoft\Remote Desktop Connection Manager>
-Run RDCMan.exe from the Google Cloud SDK Shell command prompt (it crashes with a generic 0xe0434352 KERNELBASE.dll .net error otherwise if you run it from anywhere else).

**Comment by taoszhanna** [comment] 2019-09-10 22:44
However, the distributed installer https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/download/1.0.6/CloudIap-Plugin-1.0.6.0.msi does not work.

**Comment by taoszhanna** [comment] 2019-09-10 22:44
Win10 Pro x64 build 1803

**Comment by jpassing** [comment] 2019-09-21 13:53
Did you install the Cloud SDK using the installer or using the Zip file?

The installer checks for the value `InstallLocation` in the registry key `SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Google Cloud SDK`  (32 bit hive) to locate the Cloud SDK -- but this key/value is only present when using the installer.

Regarding the crash when run from a different folder. Could you check if the `PATH` environment variable is set? I figure the crash might be caused by `PATH´ not being set, which again could be a result of the Cloud SDK being installed using the Zip and not using the installer.

Thanks for your feedback and sorry for the late reply.

**Comment by jpassing** [comment] 2019-09-21 14:21
Proposed fix in https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/pull/11

**Comment by taoszhanna** [comment] 2019-09-21 19:56
I installed with the installer.
The current sdk installer does not populate that value on current versions of Windows.

Also, when you are referring to the PATH variable, what is the expected value that needs to exist in PATH? And is it the current user PATH or system PATH?




--
Zachary Hanna



On Sep 21, 2019, at 7:53 AM, J. Passing <notifications@github.com> wrote:

﻿

Did you install the Cloud SDK using the installer or using the Zip file?

The installer checks for the value InstallLocation in the registry key SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Google Cloud SDK (32 bit hive) to locate the Cloud SDK -- but this key/value is only present when using the installer.

Regarding the crash when run from a different folder. Could you check if the PATH environment variable is set? I figure the crash might be caused by `PATH´ not being set, which again could be a result of the Cloud SDK being installed using the Zip and not using the installer.

Thanks for your feedback and sorry for the late reply.

**Comment by jpassing** [comment] 2019-09-22 07:19
You are right, that registry key is only populated if you do a per-machine install of the Cloud SDK, in case of a per-user install, the key is created in HKCU. The MSI's `LaunchCondition` currently only checks for HKLM and misses to check in HKCU.

Anyway, I removed the MSI's `LaunchCondition` in https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/pull/11 in order to also support Zip-based installs.

By default, the installer adds the Cloud SDK's `bin` directory to the `PATH` and the plugin currently expects that to be the case. That's a bit brittle and I fixed that in https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/pull/11 also.

I will publish a new release early next week.

**Comment by jpassing** [comment] 2019-09-23 15:14
Would you mind giving https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.10 a try?

**Comment by jpassing** [comment] 2019-10-12 07:56
Fixed in version 1.10

**Closed by jpassing** 2019-10-12 07:56 UTC

**Comment by taoszhanna** [comment] 2020-01-28 01:01
Yep verified this works in that tag.
