### ISSUE TITLE
Crash message when trying to connect (but connect is successful)

### ISSUE THREAD

**Issue by informajojo** [GoogleCloudPlatform/iap-windows-rdc-plugin#31] opened 2019-11-19 14:58 UTC
We get this error when doing "Connect server via IAP Cloud". It still connects but there is a .net error dialog visible.
************* Exception Text *************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RdcMan.ClientPanel.RecordLastFocusedServerLabel(ServerLabel label)
   at RdcMan.MainForm.RecordLastFocusedServerLabel(ServerLabel label)
   at RdcMan.ServerLabel.OnLostFocus(EventArgs e)
   at System.Windows.Forms.Control.WmKillFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jpassing** [comment] 2019-11-22 15:14
Could you share the Windows and .NET version that you are using?

`Help > About...` should show all version info.

Johannes

**Comment by informajojo** [comment] 2019-11-22 16:18
[fullcrash.txt](https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/files/3880387/fullcrash.txt)
I dont have access to this particular computer at the moment, but this is the full error. It looks like the .net version was 4.8. I will get the version info on Monday if required.

**Comment by jpassing** [comment] 2019-11-22 17:14
I am able to reproduce this issue if I set the server tree visibility to _Auto hide_ and then connect by right-clicking one of the thumbnails.

This looks like a focus issue of RDCMan itself -- I am not sure yet whether I can work around that...

**Comment by jpassing** [comment] 2019-11-28 15:34
I implemented a fix for this bug in https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.1.29. Would you mind giving this release a try and letting me know whether it fixes the issue for you?

**Comment by jpassing** [comment] 2019-12-11 14:24
I assume this is fixed? If not, please re-open the issue.

**Closed by jpassing** 2019-12-11 14:24 UTC

**Comment by informajojo** [comment] 2019-12-12 10:44
Yes I havent had the crash after updating, thanks.
